FUNCTION get_status(mnp_number VARCHAR2, mnp_end_date DATE) RETURN NUMBER IS
status_id          NUMBER := 9143217017413050064 /* Returned */;
is_volunteer       BOOLEAN;
SVC_INST_ID        NUMBER;
WORK_ORD_CREATE_ID VARCHAR2(50);
BEGIN
IF mnp_end_date IS NULL THEN
status_id := 9143217017413050066 /*Working*/;
RETURN status_id;
END IF;
SELECT MIN(t.SVC_INST_ID)
INTO SVC_INST_ID
FROM OP_EXT_SI_ID_MAP@OPOM t
WHERE t.EXT_ID = mnp_number
			AND t.EXT_ID_TY = 10
			AND t.END_DT = (SELECT MAX(END_DT) FROM OP_EXT_SI_ID_MAP@OPOM WHERE EXT_ID = t.EXT_ID);
SELECT t.WORK_ORD_CREATE_ID
INTO WORK_ORD_CREATE_ID
FROM OP_WORK_ORD@OPOM t
WHERE t.SVC_INST_ID = SVC_INST_ID
			AND t.WORK_ORD_STATUS IN ('3', '4')
			AND t.CUST_REQ_DT = (SELECT MAX(CUST_REQ_DT) FROM OP_WORK_ORD@OPOM WHERE SVC_INST_ID = t.SVC_INST_ID)
			AND t.WORK_ORD_NO = (SELECT MAX(WORK_ORD_NO) FROM OP_WORK_ORD@OPOM WHERE SVC_INST_ID = t.SVC_INST_ID);
IF WORK_ORD_CREATE_ID IN ('OPMTOS101D', 'Request For Cessation Credit') THEN
is_volunteer := FALSE;
ELSE
is_volunteer := TRUE;
END IF;
IF ADD_MONTHS(mnp_end_date, CASE WHEN is_volunteer THEN 1 ELSE 2 END) > SYSDATE AND SYSDATE > mnp_end_date THEN
status_id := 9143217017413050065 /*Maturing*/;
END IF;
RETURN status_id;
EXCEPTION
WHEN no_data_found THEN
RETURN status_id;
END;