INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (3, 'COMPLETED', 'SIMPLE_TAXI', 0.00, 1, 'order', 'ECONOMY_CLASS', 'CASH', 'F', 'CLASSICAL_MUSIC', false, false, false, false, 'null', '2015-04-29 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (4, 'COMPLETED', 'SIMPLE_TAXI', 72.00, 1, 'order', 'BUSINESS_CLASS', 'CASH', 'F', 'ROCK', false, true, true, false, 'everything is good', '2015-04-29 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (5, 'COMPLETED', 'SIMPLE_TAXI', 64.00, 1, 'order', 'ECONOMY_CLASS', 'VISA_CARD', 'F', 'ROCK', false, true, true, true, 'Not bad', '2015-04-29 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (7, 'COMPLETED', 'SIMPLE_TAXI', 36.00, 1, 'order', 'VAN', 'VISA_CARD', 'M', 'DANCE_MUSIC', false, false, false, false, 'Comfortable', '2015-04-29 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (2, 'COMPLETED', 'SIMPLE_TAXI', 30.00, 1, 'order', 'ECONOMY_CLASS', 'CASH', 'F', 'BLUES', false, false, false, false, 'null', '2015-04-24 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (11, 'COMPLETED', 'SIMPLE_TAXI', 86.00, 1, 'order', 'ECONOMY_CLASS', 'CASH', 'M', 'ELECTRONIC_MUSIC', false, true, true, true, 'everything is good', '2015-04-30 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (10, 'COMPLETED', 'SIMPLE_TAXI', 78.00, 1, 'order', 'BUSINESS_CLASS', 'CASH', 'F', 'CLASSICAL_MUSIC', false, true, true, true, 'null', '2015-04-26 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (12, 'COMPLETED', 'SIMPLE_TAXI', 75.00, 1, 'order', 'VAN', 'CASH', 'F', 'HIP_HOP', true, true, false, true, 'null', '2015-04-26 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (1, 'COMPLETED', 'SIMPLE_TAXI', 40.00, 1, 'order', 'BUSINESS_CLASS', 'VISA_CARD', 'M', 'DEFAULT', true, true, true, true, 'everything is good', '2015-04-23 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (9, 'COMPLETED', 'SIMPLE_TAXI', 65.00, 1, 'order', 'ECONOMY_CLASS', 'CASH', 'F', 'JAZZ', true, true, true, true, 'Fun driver', '2015-04-27 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (8, 'COMPLETED', 'SIMPLE_TAXI', 112.00, 1, 'order', 'BUSINESS_CLASS', 'VISA_CARD', 'F', 'BLUES', true, true, true, true, 'null', '2015-06-29 00:00:00.000000');
INSERT INTO public.taxi_order (tracking_number, status, service, price, user_id, description, car_category, way_of_payment, driver_sex, music_style, animal_transportation, free_wifi, smoking_driver, air_conditioner, comment, ordered_date) VALUES (6, 'COMPLETED', 'SIMPLE_TAXI', 70.00, 1, 'order', 'BUSINESS_CLASS', 'CASH', 'M', 'JAZZ', true, true, true, true, 'null', '2015-06-25 00:00:00.000000');



INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (1, 1, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (2, 2, ((-122.35,-142.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (3, 3, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (4, 4, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (5, 5, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (6, 6, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (7, 7, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (8, 8, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (9, 9, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (10, 10, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (11, 10, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (12, 10, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (13, 10, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (14, 11, ((-122.36,-122.343)), null, 1);
INSERT INTO public.taxi_order_item (taxi_item_id, tracking_numer, path, ordered_quantity, driver_id) VALUES (15, 12, ((-122.36,-122.343)), null, 1);
