DELETE FROM service_user;

-- password3A --
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (12345,  'vadimka2995@gmail.com',         '64bf867e6ce4a9706b5e4dfd445820712e74099db9271a0271866c410f0030e1', 'badbad2A', '+38063111111',  'M',   FALSE, TRUE,  null, null, null,      0, TRUE, '2015-05-09 21:37:19.145000');
-- password2A --
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (123456, 'rusan.rus@gmail.com',           'b982a65f648203ef88cde202a6084893c9fbe0eec798f3e33517c2eb19c6bd31', 'badbad2A', '+380635293836', 'M',   TRUE,  FALSE, null, null, 'A, B, C', 0, TRUE, '2015-05-09 21:37:19.145000');

INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (34,     'vadimka29@gmail.com',           '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:22:47.491479');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (35,     'vadimka29951@gmail.com',        '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:22:49.314070');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (36,     'serg@gmail.com',                '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:22:53.866486');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (38,     'sergey@gmail.com',              '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:26:38.256105');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (39,     'vas@gmail.com',                 '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:26:41.233337');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (41,     'vas92995@gmail.com',            '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:26:44.024153');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (42,     'rus@gmail.com',                 '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:26:47.177628');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (43,     'ruslan@gmail.com',              '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:26:48.098598');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (44,     'ruslan19@gmail.com',            '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:26:49.477859');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (45,     'ruslanka@gmail.com',            '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:26:54.514997');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (46,     'alex@gmail.com',                '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:27:01.609498');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (47,     'alexandr@gmail.com',            '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:27:03.384530');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (48,     'alexandr29@gmail.com',          '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:27:04.741360');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (49,     'alina@gmail.com',               '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:27:13.141666');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (50,     'kat9@gmail.com',                '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:27:15.561691');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (52,     'kat929@gmail.com',              '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:36:10.189150');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (53,     'ka@gmail.com',                  '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:36:13.536270');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (54,     'k@gmail.com',                   '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:36:14.349066');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (33,     'vadimne12324@gmail.com',        '17955097b428cd1275aba06b36915964',                                 'kqw1saq5', '123456789',     'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:22:46.134712');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (56,     'kfksdf@gmail.com',              '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:36:17.972226');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (57,     'kfksdfwq@gmail.com',            '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:36:19.204042');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (58,     'kfksdfwqqwe@gmail.com',         '111',                                                              'kqw1saq5', null,            'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:36:19.982722');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (68,     'vadimka299510@gmail.com',       '25f9e794323b453885f5181f1b624d0b',                                 'kqw1saq5', '123456789',     'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 23:40:57.939815');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (32,     'vadkosmos@gmail.com',           '123456789',                                                        'kqw1saq5', '545190529',     'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 00:22:42.402246');
INSERT INTO service_user (user_id, email, password, salt, phone, sex, driver, admin, group_name, car_number, driver_license, ignored_times, activated, registration_date) VALUES (69,     'vadimka299810kosmos@gmail.com', '774ef01be7f998e14b126900923fe8fa',                                 'kqw1saq5', '123456789',     'M',   TRUE,  FALSE, null, null, null,      0, TRUE, '2015-04-26 23:52:35.502659');